# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: GoTo.GoToAssistAgentDesktopConsole
PackageVersion: 5.8.1.92
PackageLocale: en-US
Publisher: GoTo
PackageName: GoToAssist Agent Desktop Console
License: Proprietary, Freeware
ShortDescription: 'GoToAssist Agent Desktop Console is a remote support solution for live end-user support & unattended computer access, featuring: improved keyboard shortcut handling, automatic updates, and multi-session support from a single instance.'
ManifestType: defaultLocale
ManifestVersion: 1.4.0
